### ISSUE TITLE
How to use in Parallel with XML Pluging?

### ISSUE THREAD

**Issue by anupam-chakraborty** [mulesoft-catalyst/mule-sonarqube-plugin#11]
We have a global SonarQube Server which has other application using XML Plugin. How can I force the project to use the Mule plugin without removing the .xml from the XML Language plugin?

**Comment by fperezpa** [comment]
Which version of Sonar are you using?

**Comment by anupam-chakraborty** [comment]
Hi,

I am using 
	* Enterprise Edition
	* Version 8.4.2 (build 36762)

Thanks,
Anupam

October 1, 2020 4:13 PM, "Franco Perez Parma" <notifications@github.com (mailto:notifications@github.com?to=%22Franco%20Perez%20Parma%22%20<notifications@github.com>)> wrote:
	Which version of Sonar are you using?

**Comment by pradeepchauhanmule** [comment]
> We have a global SonarQube Server which has other application using XML Plugin. How can I force the project to use the Mule plugin without removing the .xml from the XML Language plugin?

You can update your SonarQube Project "General Settings" to ignore the .xml in XML Plugin. This way you wont affect rest of the applications.

**Comment by anupam-chakraborty** [comment]
But that would stop other XML from working. I mean XML which are not Mule Specific...


Thanks,
Anupam Chakraborty
Solution Architect | RDT - BAI
Slalom
Irvine, CA 92618 | USA | Pacific Time
+1 201 699 6936 | anupam.chakraborty@slalom.com
________________________________

**Comment by pradeepchauhanmule** [comment]
You mean XML files within your Mule project which are not Mule flows ? For those you can write your own custom rules under the Mule rules.

But XML files in other non-mule projects wont get affected since you updated only your project general settings to ignore .xml in the XML plugin.

**Comment by fperezpa** [comment]
Hi @anupam-chakraborty, what @pradeepchauhanmule is saying is correct. At the project level, go to Administration and remove the extension .xml. That will allow you to run this plugin.
As you are not modifying anything from the general Administration the other projects will run as usual.

<img width="1260" alt="Screen Shot 2020-10-11 at 8 39 54 PM" src="https://user-images.githubusercontent.com/19441093/95693501-0dbf2d00-0c03-11eb-915a-3810b050bb2e.png">

Please let us know is that works for you. To run it for the first time, maybe you will you to do it at the general level so you could see the protect but then you could roll it back and updating it at the project level.

**Comment by anupam-chakraborty** [comment]
Hi,

Let me try this out and let you know. Thanks for the help around this.

**Comment by fperezpa** [comment]
I guess you also will have to update the mule plugin so it doesn't interfere with the rest of the projects. 
You could put any extension to make it work.
For example:
![Uploading Screen Shot 2020-10-11 at 9.18.15 PM.png…]()

Hope this helps.

**Comment by anupam-chakraborty** [comment]
We are testing this. Will close as soon as I can finish the testing with the necessary update.

**Comment by fperezpa** [comment]
I will close this issue. Please let us know if you have any other issue
