### ISSUE TITLE
When deploying to Kubernetes, the service stops and complains that the jar is not a plugin

### ISSUE THREAD

**Issue by palumbo67** [mulesoft-catalyst/mule-sonarqube-plugin#32]
When I download the source code, build it using Maven and package it, I get the error that the jar file is not a plugin. Do we know why this is happening? This was working when I deployed it in October 2020. I tried deploying version 1.0.2 but I get the same problem. 

Here is a screenshot of the plugins in `confs/extensions/plugins`
![image](https://user-images.githubusercontent.com/85320387/120723228-5895f980-c49f-11eb-9314-cc12bab104fe.png)

Error Message: 2021.06.03 23:06:09 ERROR web[][o.s.s.p.Platform] Web server startup failed: File is not a plugin. Please delete it and restart: /opt/sq/extensions/plugins/mule-validation-sonarqube-plugin-1.0.4-mule.jar

**Comment by chirubtech** [comment]
@palumbo67 not sure you are generating the jar using the following command. Can you please confirm?
`mvn clean package sonar-packaging:sonar-plugin -Dlanguage=mule`

**Comment by palumbo67** [comment]
I am using the Maven task in Azure Devops, so this is the output...
`C:\windows\system32\cmd.exe /D /S /C "C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\mvn.cmd -f D:\a\1\s\pom.xml clean package"`

**Comment by chirubtech** [comment]
Following command should work for you.
C:\windows\system32\cmd.exe /D /S /C "C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\mvn.cmd -f D:\a\1\s\pom.xml clean package sonar-packaging:sonar-plugin -Dlanguage=mule"

**Comment by palumbo67** [comment]
So I have included those arguments in my maven command which looks like this:
`C:\Windows\system32\cmd.exe /D /S /C "C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.1\bin\mvn.cmd -f D:\a\1\s\mule-sonarqube-plugin\pom.xml sonar-packaging:sonar-plugin "-Dlanguage=mule" clean package"
`

```
And I am getting a compile error
[INFO] 
[INFO] --- sonar-packaging-maven-plugin:1.17:sonar-plugin (default-cli) @ mule-validation-sonarqube-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.877 s
[INFO] Finished at: 2021-06-04T16:56:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.sonar-packaging-maven-plugin:sonar-packaging-maven-plugin:1.17:sonar-plugin (default-cli) on project mule-validation-sonarqube-plugin: Plugin class not found: 'com.mulesoft.services.tools.sonarqube.MulePlugin -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by gh-vadepu** [comment]
@palumbo67 , were you able yo resolve this issue ?
Actually i am also facing similar issue, where my sonarqube enterprise edition (8.6.1) is hosted on kubernetes cluster.
When i add the three plugin git urls of plugin jar, rules-3 and 4 xml in my helm charts , when install the helm chart , it says install but the git commit gives as null , attached is the error , even though i pass the rules-3.xml url still by default throws same error :

https://github.com/mulesoft-catalyst/mule-sonarqube-plugin/releases/download/1.0.4/mule-validation-sonarqube-plugin-1.0.4-mule.jar
https://github.com/mulesoft-catalyst/mule-sonarqube-plugin/releases/download/1.0.4/rules-3.xml
https://github.com/mulesoft-catalyst/mule-sonarqube-plugin/releases/download/1.0.4/rules-4.xml

<img width="1094" alt="Screenshot 2021-08-10 at 8 01 24 PM" src="https://user-images.githubusercontent.com/74282140/128890247-03b5f658-95b9-4b29-bbf6-ded88d2c7cd9.png">
c643488.png">

**Comment by palumbo67** [comment]
I was able to resolve the issue.

**Comment by hectoralicea** [comment]
> I was able to resolve the issue.

Can you describe how? I am too running into similar issues
